import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

// eslint-config-next ships native flat config from 16 onwards, so the shareable
// configs are spread directly. Until then they were eslintrc-format and came
// through FlatCompat from @eslint/eslintrc, which 16 breaks: it hands back a
// self-referencing object and the validator dies inside JSON.stringify
// ("property 'react' closes the circle").
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    // next-env.d.ts is generated by Next on every build and contains a
    // triple-slash reference that next/typescript itself forbids. `next lint`
    // skipped it implicitly; the ESLint CLI does not, so say so here.
    ignores: ["node_modules/**", ".next/**", "lib/generated/**", "next-env.d.ts"],
  },
  {
    // A claim outside redeemToken's transaction spends the link before the
    // work it authorises, and a failed write then leaves it dead (#50, #91).
    // The module client satisfies consumeToken's parameter type too, so this
    // rule is what actually keeps new redeem paths on the helper.
    //
    // Matched by pattern, not by a list of exact specifiers: any relative depth
    // (`../../lib/tokens`), the alias, or an explicit extension all resolve to
    // the same module, and an exact list let every spelling it did not name
    // through. Static imports and re-exports only — a dynamic `import()` or a
    // `require` is not something this rule can see.
    //
    // Kept as a lint rule on purpose (#134). Moving redeemToken into
    // lib/tokens.ts and dropping the consumeToken export would enforce this by
    // the module system instead, but lib/tokens.test.ts would then have to test
    // the claim through a mocked transaction rather than directly — and those
    // tests pin exactly the claim semantics this rule protects. A dynamic import
    // of consumeToken would stand out in review.
    files: ["**/*.{ts,tsx,js,jsx,mjs}"],
    ignores: ["lib/token-redeem.ts", "**/*.test.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              regex: "(^|/)tokens(\\.[cm]?[jt]sx?)?$",
              importNames: ["consumeToken"],
              message: "Redeem through redeemToken from @/lib/token-redeem instead.",
            },
          ],
        },
      ],
    },
  },
];

export default eslintConfig;
