import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

// eslint-config-next ships native flat config from 16 onwards, so the shareable
// configs are spread directly. Until then they were eslintrc-format and came
// through FlatCompat from @eslint/eslintrc, which 16 breaks: it hands back a
// self-referencing object and the validator dies inside JSON.stringify
// ("property 'react' closes the circle").
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    // next-env.d.ts is generated by Next on every build and contains a
    // triple-slash reference that next/typescript itself forbids. `next lint`
    // skipped it implicitly; the ESLint CLI does not, so say so here.
    ignores: ["node_modules/**", ".next/**", "lib/generated/**", "next-env.d.ts"],
  },
];

export default eslintConfig;
