import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

// eslint-config-next ships native flat config from 16 onwards, so the shareable
// configs are spread directly. Until then they were eslintrc-format and came
// through FlatCompat from @eslint/eslintrc, which 16 breaks: it hands back a
// self-referencing object and the validator dies inside JSON.stringify
// ("property 'react' closes the circle").
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    // next-env.d.ts is generated by Next on every build and contains a
    // triple-slash reference that next/typescript itself forbids. `next lint`
    // skipped it implicitly; the ESLint CLI does not, so say so here.
    ignores: ["node_modules/**", ".next/**", "lib/generated/**", "next-env.d.ts"],
  },
  {
    // Three React Compiler rules arrive as errors with eslint-config-next 16 and
    // fire on code that predates them — eight times, five of those inside
    // PuzzleBoard, which has no test coverage at all (jsdom has no canvas).
    //
    // They are warnings here, not disabled: every one points at something real
    // (cascading renders, refs read during render), and #84 tracks fixing them
    // deliberately, with the board exercised in a browser. Turning them off
    // would throw the findings away; leaving them as errors would mean
    // refactoring untested canvas code inside a framework upgrade, which is how
    // subtle board bugs ship. Drop this block once #84 closes.
    name: "jigsaw/react-compiler-rules-pending-84",
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/purity": "warn",
    },
  },
];

export default eslintConfig;
